name: Question
description: Ask about something here.
labels: ["question", "status: pending triage"]
body:
  - type: textarea
    attributes:
      label: What is your question?
    validations:
      required: true

  - type: dropdown
    id: buildVersion
    attributes:
      label: "What version are you using?"
      description: "You HAVE to answer this."
      options:
      # add a version to these options before making a release please.
      # - stinko
          - "No Selected Version"
          - "1.48.0"
          - "1.47.0"
          - "1.46.0"
          - "1.45.0"
          - "1.44.0"
          - "1.43.0"
          - "1.42.0"
          - "1.41.0"
          - "1.40.0"
          - "1.39.0"
          - "1.38.0"
          - "1.37.0"
          - "1.36.0"
          - "1.35.0"
          - "Version Lower than 1.35.0"
    validations:
      required: true

  - type: dropdown
    id: currentBuildCheck
    attributes:
      label: "Did you check if the problem occurs in the latest build?"
      description: "You don't need to answer this if this is happening on the latest version."
      options:
        - "No"
        - "Yes"
    validations:
      required: false

  - type: dropdown
    id: commitBuildCheck
    attributes:
      label: "Commit build or Release build?"
      options:
        - "Release build"
        - "Commit Build of latest version."
        - "Older commit build of the latest version."
    validations:
      required: true

  - type: dropdown
    id: knownIssueCheck
    attributes:
      label: "Did you check if the problem is in the pinned issue?"
      description: "[Click me here to check if there is.](https://github.com/JordanSantiagoYT/FNF-JS-Engine/issues/1031)"
      options:
        - "No"
        - "Yes"
    validations:
      required: true

  - type: dropdown
    id: dupeCheck
    attributes:
      label: "Did you check if there's any similar issues?"
      description: "Go to the search bar on the issues tab and see if there is."
      options:
        - "No"
        - "Yes"
    validations:
      required: true

  - type: textarea
    id: cmdLogs
    attributes:
      label: "Command Prompt/Terminal logs/Crash logs (if existing)"
    validations:
      required: false
